language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=microshop/webui
    - IMAGE_VERSION=$IMAGE:$COMMIT

before_script:
  - docker build -t $IMAGE:$COMMIT .
  - docker tag $IMAGE:$COMMIT $IMAGE:latest
  - docker tag $IMAGE:$COMMIT $IMAGE:travis-$TRAVIS_BUILD_NUMBER

script:
  - docker version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $IMAGE

  # Install kubernetes and set config
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

  - kubectl config set-credentials default --username=${GKE_USERNAME} --password=${GKE_PASSWORD}
  - kubectl config set-cluster default --server=${GKE_SERVER} --insecure-skip-tls-verify=true
  - kubectl config set-context default --cluster=default --user=default
  - kubectl config use-context default
  #- kubectl rolling-update webui --image=$IMAGE_VERSION
  - kubectl set image deployment/webui webui=$IMAGE_VERSION --namespace=microshop
  #- kubectl apply -f ./deployment/webui-deployment.yml